### ISSUE TITLE
ICP function not working?

### ISSUE THREAD

**Issue by greglahsal21** [zarquon42b/mesheR#10]
So, I have imported a model to use as the reference. I then defined a fit function with the icp function as a part of it. I applied that function to a series of meshes, but for some reason the output is identical to the original meshes.

Here is the code:
`fitter <- function(x,i) {
  target <- vcgImport(meshfiles[x])
  icpfit <- icp(reference,target,iterations=i,type="rigid")
  return(icpfit)
}

for (x in 2:length(meshfiles)) {
  print(x)
  tmpfit <- fitter(x,200)
  vcgPlyWrite(tmpfit,paste0("icp/",gsub(".stl","",basename(meshfiles[x]))))
}`

**Comment by zarquon42b** [comment]
The code looks reasonable and I have no idea, what went wrong there, do you get any error messages? Are the meshes reasonably close together? Did you try initializing with `pcaAlign=T`? I can assure you, that the icp function works fine in general, as I am using it on a daily basis ;)
Does the function work, when called outside the loop?
BTW: these github issues are for reporting actual bugs and not a user forum dealing with fixing user errors. If you have a problem, feel free to write me a private email.
