### ISSUE TITLE
Displaying Transforms?

### ISSUE THREAD

**Issue by greglahsal21** [zarquon42b/mesheR#8]
How would you get out a transform and display the glyphs showing the deformation using AmbergRegister? Or if you can't can you save the transform as an h5 file to display it in another program?

**Comment by zarquon42b** [comment]
There is no deformation, as AmberRegister is a deformation of a mesh and not a deformation in ambient space. You can try mesheR::createDisplacementField which gives you a matrix of 3D-points and an associated matrix of displacement vectors.
