### ISSUE TITLE
Landmark Registration with Procrustes

### ISSUE THREAD

**Issue by stevenagl12** [zarquon42b/mesheR#9]
How do you perform normal landmark registration with Procrustes? Especially, how do you perform both partial Procrustes for the rigid alignment without scaling, and full Procrustes with scaling to get pure shape correspondence?

**Comment by zarquon42b** [comment]
You can do this in Morpho with the function ProcSym or ProcGPA, where you also can specify the type of alignment (full, partial, rigid).
